SELECT USUARIO.IDUSUARIO, (PERSONA.NOMBRE+' '+PERSONA.APELLIDO)AS NOMBRECOMPLETO, 
       USUARIO.NOMBREUSER, ROL.NOMBRE AS NOMBREROL, USUARIOROL.FECHAASIGNA
FROM     PERSONA INNER JOIN
                  USUARIO ON PERSONA.IDPERSONA = USUARIO.IDPERSONA INNER JOIN
                  USUARIOROL ON USUARIO.IDUSUARIO = USUARIOROL.IDUSUARIO INNER JOIN
                  ROL ON USUARIOROL.IDROL = ROL.IDROL
SELECT PERSONA.IDPERSONA, (PERSONA.NOMBRE+' '+PERSONA.APELLIDO)AS NOMBRECOMPLETO,
CLIENTE.TIPOCLIENTE, CLIENTE.CODIGOCLIENTE, CLIENTE.ESTADO
FROM     CLIENTE INNER JOIN
                  PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA

SELECT PRODUCTO.IDPRODUCTO, PRODUCTO.NOMBRE, TIPOPROD.NOMBRE AS TIPO, MARCA.NOMBRE AS MARCAPRODUCTO, PRODUCTO.CODIGOBARRA, PRODUCTO.UNIDAD, PRODUCTO.DESCRIPCION, PRODUCTO.ESTADO
FROM     PRODUCTO INNER JOIN
                  TIPOPROD ON PRODUCTO.IDTIPOPROD = TIPOPROD.IDTIPOPROD INNER JOIN
                  MARCA ON PRODUCTO.IDMARCA = MARCA.IDMARCA

SELECT PRODUCTO.IDPRODUCTO, PRODUCTO.NOMBRE AS NOMBREPRODUCTO, PROVEEDOR.NOMBRE AS NOMBREPROVEEDOR, PROVEE.FECHA, PROVEE.PRECIO
FROM     PROVEE INNER JOIN
                  PRODUCTO ON PROVEE.IDPRODUCTO = PRODUCTO.IDPRODUCTO INNER JOIN
                  PROVEEDOR ON PROVEE.IDPROVEEDOR = PROVEEDOR.IDPROVEEDOR

SELECT PROVEEDOR.IDPROVEEDOR, PROVEEDOR.NOMBRE, INGRESO.FECHAINGRESO, INGRESO.TOTAL, INGRESO.ESTADO
FROM     INGRESO INNER JOIN
                  PROVEEDOR ON INGRESO.IDPROVEEDOR = PROVEEDOR.IDPROVEEDOR

SELECT CLIENTE.IDCLIENTE, (PERSONA.NOMBRE+' '+PERSONA.APELLIDO)AS NOMBRE_COMPLETO, VENTA.IDVENDEDOR, VENTA.TOTAL, VENTA.ESTADO
FROM     VENTA INNER JOIN
                  CLIENTE ON VENTA.IDCLIENTE = CLIENTE.IDCLIENTE INNER JOIN
                  PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA

SELECT DV.IDVENTA,C.NOMBRE AS NOMBRE_CLIENTE,P.NOMBRE AS NOMBREPRODUCTO,DV.CANTIDAD,DV.PRECIOVENTA,DV.SUBTOTAL,V.ESTADO
FROM DETALLEVENTA DV
INNER JOIN VENTA V ON DV.IDVENTA = V.IDVENTA
INNER JOIN CLIENTE CL ON V.IDCLIENTE = CL.IDCLIENTE
INNER JOIN PRODUCTO P ON DV.IDPRODUCTO = P.IDPRODUCTO
INNER JOIN PERSONA C ON CL.IDPERSONA = C.IDPERSONA;

SELECT P.NOMBRE AS NombreProducto,DI.FECHAVENC,DI.CANTIDAD,DI.PRECIOCOSTO,DI.PRECIOVENTA,
DI.SUBTOTAL*CANTIDAD AS SUBTOTAL,DI.ESTADO
FROM DETALLEING DI
INNER JOIN INGRESO I ON DI.IDINGRESO = I.IDINGRESO
INNER JOIN PRODUCTO P ON DI.IDPRODUCTO = P.IDPRODUCTO
INNER JOIN PROVEEDOR PR ON I.IDPROVEEDOR = PR.IDPROVEEDOR

--examen consultas
SELECT CLIENTE.IDCLIENTE, PERSONA.NOMBRE, PERSONA.APELLIDO, CLIENTE.TIPOCLIENTE
FROM     CLIENTE INNER JOIN
                  PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA



SELECT PROVEEDOR.NOMBRE, SUM(INGRESO.TOTAL) AS TOTALINGRESOS
FROM INGRESO INGRESO
INNER JOIN PROVEEDOR ON INGRESO.IDPROVEEDOR = PROVEEDOR.IDPROVEEDOR
GROUP BY PROVEEDOR.NOMBRE

SELECT TOP 1 MARCA.NOMBRE , COUNT(DETALLEVENTA.IDPRODUCTO) AS TOTALVENTAS
FROM DETALLEVENTA 
INNER JOIN PRODUCTO P ON DETALLEVENTA.IDPRODUCTO = P.IDPRODUCTO
INNER JOIN MARCA  ON P.IDMARCA = MARCA.IDMARCA
GROUP BY MARCA.NOMBRE

SELECT SUM(UNIDAD) AS CANTIDADTOTAL
FROM PRODUCTO;
select nombre,unidad from PRODUCTO--todos
select* from PRODUCTO

SELECT PRODUCTO.NOMBRE AS NOMBREPRODUCTO, PRODUCTO.CODIGOBARRA , DETALLEING .FECHAVENC 
FROM DETALLEING 
INNER JOIN PRODUCTO ON DETALLEING .IDPRODUCTO = PRODUCTO.IDPRODUCTO
WHERE DETALLEING.FECHAVENC BETWEEN GETDATE() AND DATEADD(DAY, 30, GETDATE())

--6
SELECT (PERSONA.NOMBRE+' '+PERSONA.APELLIDO) AS NOMBREVENDEDOR,COUNT(DETALLEVENTA.IDPRODUCTO) AS CANTIDADPRODUCTOSVENDIDOS
FROM VENTA 
INNER JOIN USUARIO ON VENTA.IDVENDEDOR = USUARIO.IDUSUARIO
INNER JOIN PERSONA ON USUARIO.IDPERSONA = PERSONA.IDPERSONA
INNER JOIN DETALLEVENTA ON VENTA.IDVENTA = DETALLEVENTA.IDVENTA
GROUP BY PERSONA.NOMBRE, PERSONA.APELLIDO

---7
SELECT CLIENTE.IDCLIENTE,(PERSONA.NOMBRE+' '+ PERSONA.APELLIDO) AS NOMBRECOMPLETO, SUM(VENTA.TOTAL) AS TOTALINGRESOS
FROM VENTA 
INNER JOIN CLIENTE ON VENTA.IDCLIENTE = CLIENTE.IDCLIENTE
INNER JOIN PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA
GROUP BY CLIENTE.IDCLIENTE,PERSONA.NOMBRE, PERSONA.APELLIDO

---8
SELECT TOP 1 PR.NOMBRE AS NOMBRE_PROVEEDOR
FROM PROVEEDOR PR
JOIN PROVEE PV ON PR.IDPROVEEDOR = PV.IDPROVEEDOR
GROUP BY PR.NOMBRE
ORDER BY SUM(PV.CANTIDAD) DESC;

SELECT TOP 1 PR.NOMBRE AS NOMBRE_PROVEEDOR
FROM PROVEEDOR PR
JOIN DETALLEING DI ON PR.IDPROVEEDOR = DI.IDPROVEEDOR
GROUP BY PR.NOMBRE
ORDER BY COUNT(DI.IDDETALLEING) DESC;









