create database GESTIONV;

CREATE TABLE VENTA (
IDVENTA INT IDENTITY (1,1) NOT NULL,
FECHA DATETIME NOT NULL,
TOTAL MONEY NOT NULL,
PRIMARY KEY (IDVENTA),
);

CREATE TABLE PRODUCTO(
IDPRODUCTO INT IDENTITY (1,1) NOT NULL,
NOMBRE NVARCHAR (100) NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
PRIMARY KEY (IDPRODUCTO),
);

CREATE TABLE DETALLEVENTA (
IDDETALLEVENTA INT IDENTITY (1,1) NOT NULL,
IDVENTA INT NOT NULL,
IDPRODUCTO INT NOT NULL,
CANTIDAD  INT NOT NULL,
PRECIOUNITARIO MONEY NOT NULL,
TOTALDETALLE MONEY NOT NULL,
PRIMARY KEY (IDDETALLEVENTA),
FOREIGN KEY (IDVENTA) REFERENCES VENTA (IDVENTA),
FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO),
);



insert into VENTA values (CONVERT(DATETIME, '2022-09-01 12:47:29', 120),95);
insert into VENTA values (CONVERT(DATETIME, '2022-10-21 12:50:56', 120),20);
insert into VENTA values (CONVERT(DATETIME, '2023-01-12 17:34:09', 120),45);
insert into VENTA values (CONVERT(DATETIME, '2023-02-09 11:40:10', 120),30);
insert into VENTA values (CONVERT(DATETIME, '2023-05-18 09:27:20', 120),185);

SELECT* FROM VENTA


insert into PRODUCTO  values ('Hamburguesa', 30);
insert into PRODUCTO values ('Fiambres', 35);
insert into PRODUCTO values ('Costilla', 45);
insert into PRODUCTO  values ('KitKat',20);
insert into PRODUCTO  values ('Nan',10);
insert into PRODUCTO  values ('Nido',15);
insert into PRODUCTO values ('NesCafe',20);
insert into PRODUCTO  values ('Nesquik', 25);
insert into PRODUCTO  values ('Chocapic', 30);
insert into PRODUCTO values ('Mayonesa',35);

select* from PRODUCTO

INSERT INTO DETALLEVENTA VALUES (1,	1, 2, 30, 60);
INSERT INTO DETALLEVENTA VALUES (2,	4, 1, 20, 20);
INSERT INTO DETALLEVENTA VALUES (3,	6, 3, 15, 45);
INSERT INTO DETALLEVENTA VALUES (4,	9, 1, 30, 30);
INSERT INTO DETALLEVENTA VALUES (5,	10,	4, 35, 140);
INSERT INTO DETALLEVENTA VALUES (1, 2, 1, 35, 35);
INSERT INTO DETALLEVENTA VALUES (5, 3, 1, 45, 45);

SELECT* FROM DETALLEVENTA


