--DDL (LENGUAJE DE DEFINICION DE DATOS):CREATE, ALTER, DROP, TRUNCATE
CREATE DATABASE ARBOLGENE;
GO
USE ARBOLGENE;
GO
-- Crear tabla Persona
CREATE TABLE PERSONA(
    ID_PERSONA INT NOT NULL IDENTITY(1,1)PRIMARY KEY,
    NOMBRES VARCHAR(25),
    APELLIDO_PATERNO VARCHAR (25),
	APELLIDO_MATERNO VARCHAR (25),
	CI VARCHAR (25),
	EXPEDIDO VARCHAR(10),
	SEXO CHAR (1) NOT NULL,
	FECHA_NACIMIENTO DATE);
GO
CREATE TABLE TIPO_RELACION(
   ID_TIRELACION INT NOT NULL IDENTITY PRIMARY KEY,
   DESCRIPCION VARCHAR(50));
GO
CREATE TABLE RELACION(
  --ID_RELACION INT NOT NULL IDENTITY,
  ID_PP INT NOT NULL,
  ID_PH INT NOT NULL,
  ID_TR INT NOT NULL,
  ID_PERS INT NOT NULL,
  --PRIMARY KEY (ID_RELACION),
  FOREIGN KEY(ID_PP)REFERENCES PERSONA(ID_PERSONA),
  FOREIGN KEY(ID_PH)REFERENCES PERSONA(ID_PERSONA),
  FOREIGN KEY(ID_TR)REFERENCES TIPO_RELACION(ID_TIRELACION)
  );
GO

-- DATOS PERSONA
INSERT INTO PERSONA(NOMBRES, APELLIDO_PATERNO,APELLIDO_MATERNO,CI,EXPEDIDO,SEXO,FECHA_NACIMIENTO) 
VALUES
       ('ROSAURA','GARECA','TOLABA','94878378','TJ','M','19/06/1918'),
	   ('TOMAS','CADENA','RUIZ','60246478','TJ','H','11/05/1917'),
	   ('ANA MARIA','CADENA','GARECA','12378904','TJ','M','05/11/1951'),
	   ('ROBERTO','CADENA','GUERRRO','68903231','TJ','H','11/05/1949'),
       ('RAQUEL','CADENA','CADENA','18975432','TJ','M','12/06/1979'),
	   ('JUAN','ORTIZ','BAUTISTA','24678902','CH','H','28/08/1974'),
	   ('CELESTE CAMILA','ORTIZ','CADENA','76879890','TJ','M','06/04/2003'),
	   ('WENDY ANGELINA','ORTIZ','CADENA','35566882','TJ','M','05/04/2012'),
	   ('MARTHA','CADENA','CADENA','56789021','TJ','M','19/04/1942'),
	   ('DOMINGO','CADENA','CADENA','65432197','TJ','H','09/06/1937'),
	   ('MARIA JOSE',NULL,'CADENA','10674525 C','TJ','M','28/08/2016'),
	   ('CRISTIAN','CADENA','RODRIGUEZ','56432179','TJ','H','05/03/2009');

INSERT INTO TIPO_RELACION(DESCRIPCION) VALUES
('Padre'),
('Madre'),
('Abuelo'),
('Abuela'),
('Hijo'),
('Hija'),
('Hermano'),
('Hermana'),
('Nieto'),
('Nieta'),
('Bisabuelo'),
('Bisabuela'),
('Bisnieto'),
('Bisnieta'),
('Tío'),
('Tía'),
('Primo'),
('Prima'),
('Esposo'),
('Esposa');

-- RELACIONES
INSERT INTO RELACION(ID_PP,ID_TR,ID_PH) VALUES
(1, 2, 5), -- Bisabuelo -> Abuelo
(2, 3, 3), -- Abuelo -> Padre
(3, 4, 7); -- Padre -> Bisnieto
DROP TABLE PERSONA